services:
  web:
    build: .
    ports:
      - "6000:6000"
    environment: 
      - REDIS_HOST=redis 
      - REDIS_PORT=6379 
      - MYSQL_HOST=mysql 
      - MYSQL_USER=root 
      - DB_PASSWORD_FILE=/run/secrets/mysql_root_password 
      - MYSQL_DATABASE=mydb
    depends_on:
      - redis
      - mysql
    secrets:
      - mysql_root_password

  mysql:
    image: mysql:8.0
    environment: 
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=mydb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_root_password

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt

volumes:
  mysql_data:
  redis_data: