version: '3.9'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es-lab
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  web:
    image: prakhar1989/foodtrucks-web
    container_name: web-lab
    ports:
      - "5000:5000"
    depends_on:
      es:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  esdata1:
